import Head from "next/head";
import AboutUs from "../components/AboutUs";
import Main from "./../components/Main";
import Agenda from "./../components/Agenda";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Main />
      <AboutUs />
      <Agenda />
    </div>
  );
}
